### ISSUE TITLE
pip installs wrong tagging package

### ISSUE THREAD

**Issue by qiemem** [emencia/emencia-django-newsletter#23]
When I run 

```
pip install -e git+https://github.com/Fantomas42/emencia-django-newsletter.git#egg=emencia.django.newsletter
```

pip installs the package 'tagging' as a dependency. This (as far as I can tell) is an old version of the tagging library and does not work with the django 1.2.x or dev. It should be installing 'django-tagging' instead.

**Comment by Fantomas42** [comment]
Hi qiemem,

thank you for the report. I have fixed it in 
Fantomas42/emencia-django-newsletter@bcb379e22c15d1b1928bf6521c019c0a321affd9

Regards

**Comment by qiemem** [comment]
Thanks for the quick fix! However, looks like you forgot the comma after 'django-tagging' in setup.py. It's trying to find django-taggingvobject instead of django-tagging.

**Comment by Fantomas42** [comment]
Shit...
Fixed in Fantomas42/emencia-django-newsletter@91a1523edb64b2a387c8c2b123067f8f88ad2f2f

Thank you for your vigilance.

**Comment by qiemem** [comment]
Perfect! Thanks!
